name: C++ Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install g++
        run: sudo apt-get update && sudo apt-get install g++ -y

      - name: Compile all programs
        run: |
          g++ 1D_Array_Frequency/main.cpp -o 1D_Array_Frequency
          g++ 2D_Array_MatrixMultiplication/main.cpp -o 2D_Array_MatrixMultiplication
          g++ Function_SwapNumbers/main.cpp -o Function_SwapNumbers
          g++ Pattern_Diamond/main.cpp -o Pattern_Diamond
          g++ PointerToFunction_Calculator/main.cpp -o PointerToFunction_Calculator
          g++ PointerToStructure_Pointer/main.cpp -o PointerToStructure_Pointer
          g++ Recursion_SumOfDigits/main.cpp -o Recursion_SumOfDigits
          g++ String_Palindrome/main.cpp -o String_Palindrome
          g++ Structure_StudentAverage/main.cpp -o Structure_StudentAverage
          g++ Unique_MatrixTranspose/main.cpp -o Unique_MatrixTranspose
