name: C++ Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install g++
      run: sudo apt-get install g++

    - name: Compile all programs
      run: |
        g++ -std=c++11 1D_Array_Frequency/main.cpp -o 1D_Array_Frequency/frequency
        g++ -std=c++11 2D_Array_MatrixMultiplication/main.cpp -o 2D_Array_MatrixMultiplication/matrix
        g++ -std=c++11 Function_SwapNumbers/main.cpp -o Function_SwapNumbers/swap
        g++ -std=c++11 Pattern_Diamond/main.cpp -o Pattern_Diamond/diamond
        g++ -std=c++11 PointerToFunction_Calculator/main.cpp -o PointerToFunction_Calculator/calculator
        g++ -std=c++11 PointerToStructure_Pointer/main.cpp -o PointerToStructure_Pointer/point
        g++ -std=c++11 Recursion_SumOfDigits/main.cpp -o Recursion_SumOfDigits/sum
        g++ -std=c++11 String_Palindrome/main.cpp -o String_Palindrome/palindrome
        g++ -std=c++11 Structure_StudentAverage/main.cpp -o Structure_StudentAverage/student
        g++ -std=c++11 Unique_MatrixTranspose/main.cpp -o Unique_MatrixTranspose/transpose
